apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: front-end
    tier: dev
spec:
  ports:
    - port: 80
      nodePort: 30008
      targetPort: 80
  type: NodePort
  selector:
    app: myapp
